version: '3.1'

services:

    database:
        image: mariadb:latest
        container_name: MariaDb_RS_Log
        restart: always
        build:
            context: ../sql
            dockerfile: ./Dockerfile
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: MyDB@123

    #api-Log:
    #    image: 

    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
