version: '3.1'

services:

    maria-db:
        image: mariadb:latest
        container_name: RS_Log_MariaDb
        restart: always
        build:
            context: ../sql
            dockerfile: ./Dockerfile
        ports:
            - 3306:3306
        #expose:
        #    - 3306
        environment:
            MYSQL_ROOT_PASSWORD: MyDB@123

    api-log:
        image: rs_log_api:latest
        container_name: RS_Log_API
        restart: always
        build:
            context: ../src
            dockerfile: ./RS.Log.API/Dockerfile
        ports:
            - 5000:80
            #- 443:443
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+5000
            #- ASPNETCORE_URLS=https://+:5001;http://+5000
        depends_on:
            - maria-db

